# Generated by Django 5.1.2 on 2024-10-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_notemodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
