# Generated by Django 5.1.2 on 2024-10-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_notemodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
